### ISSUE TITLE
Is this really non-contrastive learning?

### ISSUE THREAD

**Issue by KegangWangCCNU** [CVRL/SiNC-rPPG#1] opened 2023-11-19 15:49 UTC
Hi,

Impressive work, it looks so simple.  

In my view, the core of the work consists of three types of loss: Bandwidth, Sparsity, and Variance, which are referred to as `IPR`, `SNR`, and `EMD` in the code. Both IPR and SNR are weakly supervised terms based on prior knowledge. To prevent model collapse into trivial solutions, an EMD term is introduced.

EMD essentially constructs negative pairs by forcing the model to output a uniformly distributed psd within a batch. This effectively compares samples within a batch to ensure their distances are maximized as much as possible. Consider this scenario: if the batch size is 1, then EMD cannot function because it's impossible to construct negative pairs.

EMD does not completely solve the problem of model collapse into trivial solutions; it cannot guarantee that psd distributions produced by models positively correlate with ground truth labels—sometimes models may just randomly distribute outputs within bandwidth.

Based on my replication results, convergence is not very stable; sometimes good outcomes can be achieved while other times they're quite poor.

Looking forward to more code releases from the author!

**Comment by Apricityh** [comment] 2023-11-22 10:03
@KegangWangCCNU Your summary is accurate, and I've encountered a similar issue during my reproductions. While some results are promising, there are certain combinations that exhibit extremely poor performance. Do you happen to know the reason behind this, and do you have any effective methods for analyzing and addressing this issue? Looking forward to your response.

**Comment by Jemspeth** [comment] 2023-11-22 13:47
@KegangWangCCNU
Thank you for your interest in our work! I believe the approach is still considered non-contrastive, since there isn't a direct comparison between pairs of input samples. Rather, the EMD loss encourages some variance over the healthy pulse rate range. In our ablation studies, we were able to train some models with just the IPR and SNR losses, indicating that you could drop the batch size down to 1 there. In our supplementary material, we also show that you can reduce the batch size down to 5 samples without any issue. We are working on an extension of this paper which may show some other cases to strengthen this non-contrastive argument.

Regarding the stability of model convergence, we have also encountered this with certain combinations of dataset, model architecture, and augmentations. Generally the smaller datasets require many epochs to converge (we used 200 for PURE/UBFC). We have tried different model architectures with a general finding that huge models "discover" the rPPG signal faster, but quickly overfit to that training dataset. Smaller model architectures struggle to find the rPPG signal, but generalize well once they do. Have you been using the PhysNet 3DCNN architecture? For augmentations, we also found that some architectures learn much easier without the Gaussian pixel-wise noise and the speed augmentation.

Admittedly, analyzing model convergence is fairly challenging, because convergence appears to be almost binary: either the model discovers the rPPG signal or it does not. When the model does converge, the loss goes through a complete phase shift and drops drastically. There's a recent ICML paper on this phenomenon (https://arxiv.org/pdf/2303.15438.pdf). 

@Apricityh
I would recommend using the `plot_validation_psds` flag during training to better understand what's happening. It saves plots of time/frequency predictions on the validation set each epoch, so you can see what your model is learning.

If you describe the combination of model architecture, dataset (and its size), and augmentations I may be able to give some recommended improvements.

**Comment by KegangWangCCNU** [comment] 2023-11-23 10:20
@Apricityh The problem is that EMD does not ensure that the model avoids trivial solutions, and it may converge to solutions where random sine waves are output.

Whether this method is effective depends on whether the model can "spontaneously" discover rPPG signals. If only rPPG signals are contained within the frequency band, then once the model discovers it during its random optimization process, symmetry in the model will be broken and solutions will depend on the discovered rPPG signal.

If a model does not spontaneously discover an rPPG signal, it will converge to a trivial solution where outputs are just random sine waves within the frequency band regardless of input.

If there are other time-domain signals with similar or greater intensity than rPPG signals in addition to them in the frequency band, I suspect this method would be almost ineffective as its chances of spontaneously discovering an rPPG signal would be extremely low. Therefore, I believe this method is almost unsuitable for more challenging datasets such as MMPD and COHFACE.

Thus, key to solving convergence stability issues lies in inducing discovery of an rPPG signal. A good approach might involve using classic unsupervised methods (such as POS) for weak supervision aimed at correlating POS with model output. A weakly supervised loss term called induction term could be added with very small weight; otherwise, models would merely learn from POS without achieving high performance. Once models begin converging under pseudo-label induction they should gradually phase out induction terms.

**Comment by Jemspeth** [comment] 2023-12-17 02:16
@KegangWangCCNU Regarding your comment, "If a model does not spontaneously discover an rPPG signal, it will converge to a trivial solution where outputs are just random sine waves within the frequency band regardless of input," have you actually found this to occur experimentally? I've run 100's of experiments with these loss functions and haven't found one PhysNet model that converges to random sinusoids. I have seen cases where after training for a long time the model produces band-limited signals that are not the pulse, but only sinusoids if it has found the rPPG signal. I'd guess this could occur for autoencoder architectures or very large models, but the PhysNet model is a relatively small network with only convolutional layers. It's fully-convolutional along the time domain, so mapping arbitrary input videos to sinusoids isn't a trivial solution.

The second comment, "If there are other time-domain signals with similar or greater intensity than rPPG signals...," fails to acknowledge that the rPPG signal is the only signal that is periodic within that band for ALL video samples. If someone happens to blink in the frequency band for a short portion of video, the model won't learn it, because those features aren't useful for almost all of the training samples. This also fails to acknowledge how many invariances are inherently learned with these losses. Motion is arguably the hardest noise factor for rPPG, but it is typically outside the physiological range, so the model learns to ignore motion! The same goes for for high frequency camera noise.

The DDPM dataset has a ton of motion and is very challenging for rPPG. I'd love to see experimental results on MMPD and COHFACE, but I unfortunately don't have access to those datasets at the moment. If you run those experiments and have issues, I'm happy to help. This thread has diverged somewhat from the codebase though, so I'm marking it as resolved.

**Closed as completed by Jemspeth** 2023-12-17 02:16 UTC
